"룰 기반 알고리즘"
-단점: 메모리를 많이 차지, 생성된 규칙이 많아 막상 적용하기가 어려움

In [1]:
import mlxtend
import numpy as np
import pandas as pd

In [2]:
# 데이터셋을 생성
data = np.array([
    ['우유', '기저귀', '쥬스'], # 0번 거래
    ['양상추', '기저귀', '맥주'], # 1번 거래
    ['우유', '양상추', '기저귀', '맥주'], # 2번 거래
    ['양상추', '맥주'] # 3번 거래
])

## Apriori 알고리즘

In [5]:
from mlxtend.preprocessing import TransactionEncoder # TransactionEncoder 불러오기

te = TransactionEncoder()
te_ary = te.fit(data).transform(data)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

     기저귀     맥주    양상추     우유     쥬스
0   True  False  False   True   True
1   True   True   True  False  False
2   True   True   True   True  False
3  False   True   True  False  False

In [7]:
# 연습
pd.DataFrame(te_ary)

       0      1      2      3      4
0   True  False  False   True   True
1   True   True   True  False  False
2   True   True   True   True  False
3  False   True   True  False  False

In [6]:
# 연습
te.columns_

['기저귀', '맥주', '양상추', '우유', '쥬스']

In [8]:
%%time
from mlxtend.frequent_patterns import apriori # apriori 라이브러리 불러오기

apriori(df, min_support=0.5, use_colnames=True) # 최소 지지도 설정

CPU times: user 9.4 ms, sys: 1.25 ms, total: 10.6 ms
Wall time: 9.24 ms

   support        itemsets
0     0.75           (기저귀)
1     0.75            (맥주)
2     0.75           (양상추)
3     0.50            (우유)
4     0.50       (맥주, 기저귀)
5     0.50      (기저귀, 양상추)
6     0.50       (기저귀, 우유)
7     0.75       (맥주, 양상추)
8     0.50  (맥주, 기저귀, 양상추)

## FP-Growth 알고리즘

In [9]:
# 전처리 단계는 동일
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(data).transform(data)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

     기저귀     맥주    양상추     우유     쥬스
0   True  False  False   True   True
1   True   True   True  False  False
2   True   True   True   True  False
3  False   True   True  False  False

In [10]:
%%time
from mlxtend.frequent_patterns import fpgrowth

fpgrowth(df, min_support=0.5, use_colnames=True) # fpgrowth -> apriori보다 속도가 빠름 (장점)

CPU times: user 3.19 ms, sys: 16 µs, total: 3.2 ms
Wall time: 2.96 ms

   support        itemsets
0     0.75           (기저귀)
1     0.50            (우유)
2     0.75           (양상추)
3     0.75            (맥주)
4     0.50       (맥주, 기저귀)
5     0.50      (기저귀, 양상추)
6     0.50  (맥주, 기저귀, 양상추)
7     0.50       (기저귀, 우유)
8     0.75       (맥주, 양상추)

In [13]:
# 추가
from mlxtend.frequent_patterns import association_rules

association = fpgrowth(df, min_support=0.1, use_colnames=True)
association_rules(association, metric = 'confidence', min_threshold=0.5, support_only=True)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(맥주),(기저귀),NaN,NaN,0.50,NaN,NaN,NaN,NaN
1,(기저귀),(맥주),NaN,NaN,0.50,NaN,NaN,NaN,NaN
2,(기저귀),(양상추),NaN,NaN,0.50,NaN,NaN,NaN,NaN
3,(양상추),(기저귀),NaN,NaN,0.50,NaN,NaN,NaN,NaN
4,"(맥주, 기저귀)",(양상추),NaN,NaN,0.50,NaN,NaN,NaN,NaN
5,"(맥주, 양상추)",(기저귀),NaN,NaN,0.50,NaN,NaN,NaN,NaN
6,"(기저귀, 양상추)",(맥주),NaN,NaN,0.50,NaN,NaN,NaN,NaN
7,(맥주),"(기저귀, 양상추)",NaN,NaN,0.50,NaN,NaN,NaN,NaN
8,(기저귀),"(맥주, 양상추)",NaN,NaN,0.50,NaN,NaN,NaN,NaN
9,(양상추),"(맥주, 기저귀)",NaN,NaN,0.50,NaN,NaN,NaN,NaN
10,(기저귀),(우유),NaN,NaN,0.50,NaN,NaN,NaN,NaN
11,(우유),(기저귀),NaN,NaN,0.50,NaN,NaN,NaN,NaN
12,(맥주),(양상추),NaN,NaN,0.75,NaN,NaN,NaN,NaN
13,(양상추),(맥주),NaN,NaN,0.75,NaN,NaN,NaN,NaN